### ISSUE TITLE
Design breakage in BoardViewController php 8.2

### ISSUE THREAD

**Issue by carlosnewmusic** [greyaz/ThemeRevision#24]
when opening the dashboard mode it appears like this
![imagen](https://github.com/greyaz/ThemeRevision/assets/19379457/6b30d58a-cd8b-4c50-8a5b-34807cc392e6)
when it should appear as it does in php version 7.4.
![imagen](https://github.com/greyaz/ThemeRevision/assets/19379457/076116e9-a8e1-4633-b67e-31ee67e43138)

**Comment by mohamad-supangat** [comment]
same here

**Comment by ballinger** [comment]
same

**Comment by greyaz** [comment]
Any error message?

**Comment by carlosnewmusic** [comment]
> Any error message?
![imagen](https://github.com/user-attachments/assets/73405893-21a0-4fa8-8b7b-d1d41566a6be)

https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

in www.web.com/?controller=ConfigController&action=index
Fatal error: Uncaught Error: Call to undefined function php_uname() in /home/user/public_html/www.web.com/app/Template/config/about.php:44 Stack trace: #0 /home/user/public_html/www.web.com/app/Core/Template.php(83): include() #1 /home/user/public_html/www.web.com/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render() #2 /home/user/public_html/www.web.com/app/Helper/LayoutHelper.php(129): Kanboard\Helper\LayoutHelper->subLayout() #3 /home/user/public_html/www.web.com/app/Controller/ConfigController.php(20): Kanboard\Helper\LayoutHelper->config() #4 /home/user/public_html/www.web.com/app/Core/Controller/Runner.php(77): Kanboard\Controller\ConfigController->index() #5 /home/user/public_html/www.web.com/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #6 /home/user/public_html/www.web.com/index.php(9): Kanboard\Core\Controller\Runner->execute() #7 {main} thrown in /home/user/public_html/www.web.com/app/Template/config/about.php on line 44
