### ISSUE TITLE
cli cronjob not working in docker environment after install ThemeRevision.

### ISSUE THREAD

**Issue by theralse** [greyaz/ThemeRevision#25]
cli cronjob shows the error message below.
It looks like the working directory not set correctly.
How to fix this issue?

```
Warning: fopen(plugins/ThemeRevision/Asset/main.min.css): Failed to open stream: No such file or directory in /var/www/kbd/plugins/ThemeRevision/Helper/ModeSwitchHelper.php on line 32

Warning: file_get_contents(plugins/ThemeRevision/Asset/dev/css/basics.css): Failed to open stream: No such file or directory in /var/www/kbd/plugins/ThemeRevision/Helper/ModeSwitchHelper.php on line 53

Warning: file_get_contents(plugins/ThemeRevision/Asset/dev/css/form-components.css): Failed to open stream: No such file or directory in /var/www/kbd/plugins/ThemeRevision/Helper/ModeSwitchHelper.php on line 53

Warning: file_get_contents(plugins/ThemeRevision/Asset/dev/css/table.css): Failed to open stream: No such file or directory in /var/www/kbd/plugins/ThemeRevision/Helper/ModeSwitchHelper.php on line 53

Fatal error: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /var/www/kbd/plugins/ThemeRevision/Helper/ModeSwitchHelper.php:33
Stack trace:
#0 /var/www/kbd/plugins/ThemeRevision/Helper/ModeSwitchHelper.php(33): fwrite(false, '')
#1 /var/www/kbd/plugins/ThemeRevision/Plugin.php(44): Kanboard\Plugin\ThemeRevision\Helper\ModeSwitchHelper->productionMode()
```

Currently I found a solution.
Pass the the working directory to docker when execute cli cronjob.
ex: `docker exec -w /var/www/kbd/ docker_name /var/www/kbd/cli cronjob`
But I don't know if there's any side effects...

**Comment by greyaz** [comment]
Try to fix the issue in the next version: 1.1.12
